// Lightweight service worker registration helper using workbox-generated sw
// This file will register the service worker generated by vite-plugin-pwa

export function registerServiceWorker() {
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', async () => {
      try {
        const registration = await navigator.serviceWorker.register('/sw.js');
        console.log('ServiceWorker registration successful with scope: ', registration.scope);

        // Listen for updates
        registration.addEventListener('updatefound', () => {
          const newWorker = registration.installing;
          if (!newWorker) return;
          newWorker.addEventListener('statechange', () => {
            if (newWorker.state === 'installed') {
              if (navigator.serviceWorker.controller) {
                // New content available, prompt the user or reload
                console.log('New content available; please refresh.');
              } else {
                // Content cached for offline use
                console.log('Content is cached for offline use.');
              }
            }
          });
        });
      } catch (err) {
        console.error('ServiceWorker registration failed: ', err);
      }
    });
  }
}
